services:
  nrw-api:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8000"
    restart: always
  nrw-app:
    build:
      context: ./nrw-app
      dockerfile: dockerfile
    ports:
      - "3000"
    restart: always
    env_file:
      - ./nrw-app/.env
  nrw-db:
    build:
      context: ./database
      dockerfile: dockerfile
    ports:
      - "5432"
  nrw-sync:
    build:
      context: ./temporal-guru
      dockerfile: dockerfile
    ports:
      - "9000"
    env_file:
      - ./temporal-guru/.env
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro   
    depends_on: 
      - nrw-api
      - nrw-app
    restart: always
